sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: hwy-sky-take-out

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wxa813ba1fe9472638
    secret: 9600ac209393dfe3b75be5b0d17ac691
